language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
before_script:
    # run black to check if some files would need reformatting
    - black --check . || true
script:
    - python manage.py test
deploy:
    run: python manage.py migrate
    on: master
